#!/usr/bin/env python3

import argparse
import ffmpeg
import numpy as np

parser = argparse.ArgumentParser(description='Find the sync between two videos')
parser.add_argument('video1', help="the first footage")
parser.add_argument("video2", help="the second footage")
args = parser.parse_args()

video1_probe = ffmpeg.probe(args.video1)
video1_stream = next((stream for stream in video1_probe['streams'] if stream['codec_type'] == 'video'), None)
video1_width = int(video1_stream['width'])
video1_height = int(video1_stream['height'])
out1, _ = (
    ffmpeg
    .input(args.video1)
    .output('pipe:', format='rawvideo', pix_fmt='rgb24')
    .run(capture_stdout=True)
)
video1_arr = (
    np
    .frombuffer(out1, np.uint8)
    .reshape([-1, video1_height, video1_width, 3])
)

video2_probe = ffmpeg.probe(args.video2)
video2_stream = next((stream for stream in video2_probe['streams'] if stream['codec_type'] == 'video'), None)
video2_width = int(video2_stream['width'])
video2_height = int(video2_stream['height'])
out2, _ = (
    ffmpeg
    .input(args.video2)
    .output('pipe:', format='rawvideo', pix_fmt='rgb24')
    .run(capture_stdout=True)
)
video2_arr = (
    np
    .frombuffer(out2, np.uint8)
    .reshape([-1, video2_height, video2_width, 3])
)

print(video1_arr.shape)
print(video2_arr.shape)